### ISSUE TITLE
Fix connect logic

### ISSUE THREAD

**Issue by Beaux44** [sockheadrps/Terrace-Dashboard#4]
Make the `ClientHandler` connect event do nothing, and move the connect logic from just above the event loop into the `DashboardHandler` so that it can be handled like all of the other events. This probably can't be done before completing #1.

The order should probably also be changed so that the client sends the connect event, which the server responds to, instead of the other way around, which would actually make it possible to finish this before splitting stats into multiple endpoints.

**Comment by Beaux44** [comment]
Additionally simplify the client checking above the loop from a match into a dictionary look up.

**Comment by sockheadrps** [comment]
Done, minus the client checking to dict instead of match. I think match is more elegant here. Might change my opinion in the future

**Comment by sockheadrps** [comment]
Okay you were right. Removed the match statement and implemented the functionality you suggested, as you know since you helped write most of it
