### ISSUE TITLE
My Ideas For Improvements

### ISSUE THREAD

**Issue by colin99d** [sockheadrps/Terrace-Dashboard#8]
Hey man, 

Saw you on reddit and thought I would leave some feedback. Overall, awesome project and I really liked using it. Here are some suggestions for improvement:

- Add your `logs/` folder to your `.gitignore`
- Use poetry for dependency management
- Use tools like black, pylint, flake8, and mypy to improve code quality
- Add better handling for bad values (like in this function: `function saveWeather(data)`)

Again great work man. Teaching yourself can be hard but is also very rewarding. Feel free to reach out if you ever wanna chat: Charlestons#0746 (discord).

**Comment by sockheadrps** [comment]
Thank you!

**Comment by sockheadrps** [comment]
Complete, thanks!
